// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 46HRUmKiZfZWKqbQxfEozQ
// Component: Rna8FYquKn5x
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 46HRUmKiZfZWKqbQxfEozQ/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: Rna8FYquKn5x/css

import Ellipse1Icon from "./icons/PlasmicIcon__Ellipse1"; // plasmic-import: ENsSDa-1NYm/icon
import Ellipse2Icon from "./icons/PlasmicIcon__Ellipse2"; // plasmic-import: MiN_Deur7jc/icon
import Group13Icon from "./icons/PlasmicIcon__Group13"; // plasmic-import: vFz1iK_DsQS/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: K-lvQp6Euev/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: FqsJO-Tspmf/icon
import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: K0ESF1w3T-l/icon
import Ellipse4Icon from "./icons/PlasmicIcon__Ellipse4"; // plasmic-import: HITutjEG6qZ/icon
import FibriefcaseIcon from "./icons/PlasmicIcon__Fibriefcase"; // plasmic-import: phYp8DCYTZv/icon
import Ellipse5Icon from "./icons/PlasmicIcon__Ellipse5"; // plasmic-import: y8Q2meerJ7I/icon
import FitrelloIcon from "./icons/PlasmicIcon__Fitrello"; // plasmic-import: 8RSwxqalTI0/icon
import Ellipse6Icon from "./icons/PlasmicIcon__Ellipse6"; // plasmic-import: sCv5g3_7Zbp/icon
import FisendIcon from "./icons/PlasmicIcon__Fisend"; // plasmic-import: J7B3FgxaJCd/icon
import Ellipse7Icon from "./icons/PlasmicIcon__Ellipse7"; // plasmic-import: X-G__MSgaPa/icon
import FigiftIcon from "./icons/PlasmicIcon__Figift"; // plasmic-import: vzfdXO3PW1e/icon
import Ellipse8Icon from "./icons/PlasmicIcon__Ellipse8"; // plasmic-import: XZvpAVp30oE/icon
import FiwifiOffIcon from "./icons/PlasmicIcon__FiwifiOff"; // plasmic-import: pLVSwvhpkI_/icon
import Ellipse9Icon from "./icons/PlasmicIcon__Ellipse9"; // plasmic-import: 94V4wShxaNy/icon
import FiglobeIcon from "./icons/PlasmicIcon__Figlobe"; // plasmic-import: ENDlV8AO6v8/icon
import Ellipse3Icon from "./icons/PlasmicIcon__Ellipse3"; // plasmic-import: 2WislIeHdO8/icon
import FicheckCircleIcon from "./icons/PlasmicIcon__FicheckCircle"; // plasmic-import: jWF9-NFYWJr/icon
import FiactivityIcon from "./icons/PlasmicIcon__Fiactivity"; // plasmic-import: zxLTQf_rHmk/icon

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  landing?: p.Flex<"div">;
  navbar?: p.Flex<"div">;
  group1?: p.Flex<"div">;
  btnSecondary?: p.Flex<"div">;
  rectangle1?: p.Flex<"div">;
  logo?: p.Flex<"div">;
  group2?: p.Flex<"div">;
  rectangle3?: p.Flex<"div">;
  brand?: p.Flex<"div">;
  group14?: p.Flex<"div">;
  slack21?: p.Flex<"div">;
  group22?: p.Flex<"div">;
  group21?: p.Flex<"div">;
  group23?: p.Flex<"div">;
  group24?: p.Flex<"div">;
  group18?: p.Flex<"div">;
  group17?: p.Flex<"div">;
  group25?: p.Flex<"div">;
  group19?: p.Flex<"div">;
  group20?: p.Flex<"div">;
  group26?: p.Flex<"div">;
  group27?: p.Flex<"div">;
  group28?: p.Flex<"div">;
  btnPrimary?: p.Flex<"div">;
  link?: p.Flex<"a"> & Partial<LinkProps>;
  rectangle2?: p.Flex<"a"> & Partial<LinkProps>;
  group4?: p.Flex<"div">;
  image3?: p.Flex<"div">;
  group6?: p.Flex<"div">;
  rectangle5?: p.Flex<"div">;
  group5?: p.Flex<"div">;
  group7?: p.Flex<"div">;
  rectangle6?: p.Flex<"div">;
  group8?: p.Flex<"div">;
  group9?: p.Flex<"div">;
  rectangle7?: p.Flex<"div">;
  rectangle8?: p.Flex<"div">;
  rectangle9?: p.Flex<"div">;
  rectangle10?: p.Flex<"div">;
  rectangle11?: p.Flex<"div">;
  rectangle12?: p.Flex<"div">;
  rectangle13?: p.Flex<"div">;
  rectangle14?: p.Flex<"div">;
  rectangle15?: p.Flex<"div">;
  rectangle16?: p.Flex<"div">;
  group29?: p.Flex<"div">;
  image4?: p.Flex<"div">;
  input?: p.Flex<"div">;
  rectangle4?: p.Flex<"div">;
  btnPrimary2?: p.Flex<"div">;
  rectangle17?: p.Flex<"div">;
};

export interface DefaultHomepageProps {}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"landing"}
            data-plasmic-override={overrides.landing}
            className={classNames(projectcss.all, sty.landing)}
          >
            <div
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames(projectcss.all, sty.navbar)}
            >
              <div
                data-plasmic-name={"group1"}
                data-plasmic-override={overrides.group1}
                className={classNames(projectcss.all, sty.group1)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cvP0
                  )}
                >
                  {"Home"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__veyR
                  )}
                >
                  {"Features"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cs0Wp
                  )}
                >
                  {"Showcase"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jNzcU
                  )}
                >
                  {"Pricing"}
                </div>
              </div>

              <div
                data-plasmic-name={"btnSecondary"}
                data-plasmic-override={overrides.btnSecondary}
                className={classNames(projectcss.all, sty.btnSecondary)}
              >
                <div
                  data-plasmic-name={"rectangle1"}
                  data-plasmic-override={overrides.rectangle1}
                  className={classNames(projectcss.all, sty.rectangle1)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zjsdJ
                  )}
                >
                  {"Sign In"}
                </div>
              </div>

              <div
                data-plasmic-name={"logo"}
                data-plasmic-override={overrides.logo}
                className={classNames(projectcss.all, sty.logo)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y0MwD
                  )}
                >
                  {"Payna"}
                </div>

                <div
                  data-plasmic-name={"group2"}
                  data-plasmic-override={overrides.group2}
                  className={classNames(projectcss.all, sty.group2)}
                >
                  <div
                    data-plasmic-name={"rectangle3"}
                    data-plasmic-override={overrides.rectangle3}
                    className={classNames(projectcss.all, sty.rectangle3)}
                  />

                  <Ellipse1Icon
                    className={classNames(projectcss.all, sty.svg__nCpf)}
                    role={"img"}
                  />

                  <Ellipse2Icon
                    className={classNames(projectcss.all, sty.svg__bsJyk)}
                    role={"img"}
                  />
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"brand"}
              data-plasmic-override={overrides.brand}
              className={classNames(projectcss.all, sty.brand)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__b9Ht
                )}
              >
                {"Trusted by\nGlobal Companies"}
              </div>

              <div
                data-plasmic-name={"group14"}
                data-plasmic-override={overrides.group14}
                className={classNames(projectcss.all, sty.group14)}
              >
                <Group13Icon
                  className={classNames(projectcss.all, sty.svg__qn1Ce)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"slack21"}
                  data-plasmic-override={overrides.slack21}
                  className={classNames(projectcss.all, sty.slack21)}
                >
                  <VectorIcon
                    className={classNames(projectcss.all, sty.svg__asWCy)}
                    role={"img"}
                  />

                  <Vector2Icon
                    className={classNames(projectcss.all, sty.svg__wrC0N)}
                    role={"img"}
                  />

                  <GroupIcon
                    className={classNames(projectcss.all, sty.svg__dlN5Z)}
                    role={"img"}
                  />
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__wbK8S)}
                  displayHeight={"30px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"91.911px" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/blank_project/images/google20151.svg",
                    fullWidth: 91.911,
                    fullHeight: 30,
                    aspectRatio: 3.066667
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__bOz6O)}
                  displayHeight={"30px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100.024px" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/blank_project/images/spotify11.svg",
                    fullWidth: 100.024,
                    fullHeight: 30,
                    aspectRatio: 3.366667
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__gQs3I)}
                  displayHeight={"30px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"87.702px" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/blank_project/images/apple111.svg",
                    fullWidth: 87.702,
                    fullHeight: 30,
                    aspectRatio: 2.933333
                  }}
                />
              </div>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__fw9Cl
              )}
            >
              {"Manage Payroll\nLike an Expert"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__pnsMs
              )}
            >
              {
                "Payna is helping you to setting up the payroll without\nrequired any finance skills or knowledge before"
              }
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__biZeI
              )}
            >
              {"For Your Business"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__gj0UX
              )}
            >
              {"WORK BETTER"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__dnr4V
              )}
            >
              {
                "We did research what your company needs and\nhere we are providing all of them just for you"
              }
            </div>

            <div
              data-plasmic-name={"group22"}
              data-plasmic-override={overrides.group22}
              className={classNames(projectcss.all, sty.group22)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2Xpx
                )}
              >
                {"Working together with your\nteam to make decisions"}
              </div>

              <div
                data-plasmic-name={"group21"}
                data-plasmic-override={overrides.group21}
                className={classNames(projectcss.all, sty.group21)}
              >
                <Ellipse4Icon
                  className={classNames(projectcss.all, sty.svg__jgZc)}
                  role={"img"}
                />

                <FibriefcaseIcon
                  className={classNames(projectcss.all, sty.svg___7Xtjy)}
                  role={"img"}
                />
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zvCld
                )}
              >
                {"Share Insights"}
              </div>
            </div>

            <div
              data-plasmic-name={"group23"}
              data-plasmic-override={overrides.group23}
              className={classNames(projectcss.all, sty.group23)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rnuHn
                )}
              >
                {"Organize the report that\neasy to be understand"}
              </div>

              <div
                data-plasmic-name={"group24"}
                data-plasmic-override={overrides.group24}
                className={classNames(projectcss.all, sty.group24)}
              >
                <Ellipse5Icon
                  className={classNames(projectcss.all, sty.svg__fPMh)}
                  role={"img"}
                />

                <FitrelloIcon
                  className={classNames(projectcss.all, sty.svg__yqwO)}
                  role={"img"}
                />
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cAu2H
                )}
              >
                {"Kanban Mode"}
              </div>
            </div>

            <div
              data-plasmic-name={"group18"}
              data-plasmic-override={overrides.group18}
              className={classNames(projectcss.all, sty.group18)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__erCom
                )}
              >
                {"See where your money goes\nand comes in business"}
              </div>

              <div
                data-plasmic-name={"group17"}
                data-plasmic-override={overrides.group17}
                className={classNames(projectcss.all, sty.group17)}
              >
                <Ellipse6Icon
                  className={classNames(projectcss.all, sty.svg__g3UzT)}
                  role={"img"}
                />

                <FisendIcon
                  className={classNames(projectcss.all, sty.svg__sJvOz)}
                  role={"img"}
                />
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__j56K4
                )}
              >
                {"Track Leads"}
              </div>
            </div>

            <div
              data-plasmic-name={"group25"}
              data-plasmic-override={overrides.group25}
              className={classNames(projectcss.all, sty.group25)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lgPt2
                )}
              >
                {"Motivate your team working\nharder and receive a gift"}
              </div>

              <div
                data-plasmic-name={"group19"}
                data-plasmic-override={overrides.group19}
                className={classNames(projectcss.all, sty.group19)}
              >
                <Ellipse7Icon
                  className={classNames(projectcss.all, sty.svg__mf5Z)}
                  role={"img"}
                />

                <FigiftIcon
                  className={classNames(projectcss.all, sty.svg__cg4T4)}
                  role={"img"}
                />
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5RI
                )}
              >
                {"Reward System"}
              </div>
            </div>

            <div
              data-plasmic-name={"group20"}
              data-plasmic-override={overrides.group20}
              className={classNames(projectcss.all, sty.group20)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4ShGs
                )}
              >
                {"Use the feature while off\nfrom internet? sure can"}
              </div>

              <div
                data-plasmic-name={"group26"}
                data-plasmic-override={overrides.group26}
                className={classNames(projectcss.all, sty.group26)}
              >
                <Ellipse8Icon
                  className={classNames(projectcss.all, sty.svg__eKDzH)}
                  role={"img"}
                />

                <FiwifiOffIcon
                  className={classNames(projectcss.all, sty.svg__re8Ip)}
                  role={"img"}
                />
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nUqe
                )}
              >
                {"Offline Mode"}
              </div>
            </div>

            <div
              data-plasmic-name={"group27"}
              data-plasmic-override={overrides.group27}
              className={classNames(projectcss.all, sty.group27)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vaQ8D
                )}
              >
                {"Working together worldwide\npeople from anywhere"}
              </div>

              <div
                data-plasmic-name={"group28"}
                data-plasmic-override={overrides.group28}
                className={classNames(projectcss.all, sty.group28)}
              >
                <Ellipse9Icon
                  className={classNames(projectcss.all, sty.svg__y4Hv7)}
                  role={"img"}
                />

                <FiglobeIcon
                  className={classNames(projectcss.all, sty.svg__jEkfB)}
                  role={"img"}
                />
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xpe56
                )}
              >
                {"189 Country"}
              </div>
            </div>

            <div
              data-plasmic-name={"btnPrimary"}
              data-plasmic-override={overrides.btnPrimary}
              className={classNames(projectcss.all, sty.btnPrimary)}
            >
              <p.PlasmicLink
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(projectcss.all, projectcss.a, sty.link)}
                component={Link}
                platform={"nextjs"}
              >
                <p.PlasmicLink
                  data-plasmic-name={"rectangle2"}
                  data-plasmic-override={overrides.rectangle2}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.rectangle2
                  )}
                  component={Link}
                  href={"/" as const}
                  platform={"nextjs"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cDmlt
                    )}
                  >
                    {"Get Started"}
                  </div>
                </p.PlasmicLink>
              </p.PlasmicLink>
            </div>

            <div
              data-plasmic-name={"group4"}
              data-plasmic-override={overrides.group4}
              className={classNames(projectcss.all, sty.group4)}
            >
              <div
                data-plasmic-name={"image3"}
                data-plasmic-override={overrides.image3}
                className={classNames(projectcss.all, sty.image3)}
              />
            </div>

            <div
              data-plasmic-name={"group6"}
              data-plasmic-override={overrides.group6}
              className={classNames(projectcss.all, sty.group6)}
            >
              <div
                data-plasmic-name={"rectangle5"}
                data-plasmic-override={overrides.rectangle5}
                className={classNames(projectcss.all, sty.rectangle5)}
              />

              <div
                data-plasmic-name={"group5"}
                data-plasmic-override={overrides.group5}
                className={classNames(projectcss.all, sty.group5)}
              >
                <Ellipse3Icon
                  className={classNames(projectcss.all, sty.svg__eeQmg)}
                  role={"img"}
                />

                <FicheckCircleIcon
                  className={classNames(projectcss.all, sty.svg__u3GAx)}
                  role={"img"}
                />
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hcRIi
                )}
              >
                {"Bulk Export"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5NvK0
                )}
              >
                {"Work faster 200%"}
              </div>
            </div>

            <div
              data-plasmic-name={"group7"}
              data-plasmic-override={overrides.group7}
              className={classNames(projectcss.all, sty.group7)}
            >
              <div
                data-plasmic-name={"rectangle6"}
                data-plasmic-override={overrides.rectangle6}
                className={classNames(projectcss.all, sty.rectangle6)}
              />

              <div
                data-plasmic-name={"group8"}
                data-plasmic-override={overrides.group8}
                className={classNames(projectcss.all, sty.group8)}
              >
                <Ellipse3Icon
                  className={classNames(projectcss.all, sty.svg___3Uyxk)}
                  role={"img"}
                />

                <FiactivityIcon
                  className={classNames(projectcss.all, sty.svg__qf8F8)}
                  role={"img"}
                />
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___8Uhtg
                )}
              >
                {"Analytics"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hlEij
                )}
              >
                {"Real time report"}
              </div>

              <div
                data-plasmic-name={"group9"}
                data-plasmic-override={overrides.group9}
                className={classNames(projectcss.all, sty.group9)}
              >
                <div
                  data-plasmic-name={"rectangle7"}
                  data-plasmic-override={overrides.rectangle7}
                  className={classNames(projectcss.all, sty.rectangle7)}
                />

                <div
                  data-plasmic-name={"rectangle8"}
                  data-plasmic-override={overrides.rectangle8}
                  className={classNames(projectcss.all, sty.rectangle8)}
                />

                <div
                  data-plasmic-name={"rectangle9"}
                  data-plasmic-override={overrides.rectangle9}
                  className={classNames(projectcss.all, sty.rectangle9)}
                />

                <div
                  data-plasmic-name={"rectangle10"}
                  data-plasmic-override={overrides.rectangle10}
                  className={classNames(projectcss.all, sty.rectangle10)}
                />

                <div
                  data-plasmic-name={"rectangle11"}
                  data-plasmic-override={overrides.rectangle11}
                  className={classNames(projectcss.all, sty.rectangle11)}
                />

                <div
                  data-plasmic-name={"rectangle12"}
                  data-plasmic-override={overrides.rectangle12}
                  className={classNames(projectcss.all, sty.rectangle12)}
                />

                <div
                  data-plasmic-name={"rectangle13"}
                  data-plasmic-override={overrides.rectangle13}
                  className={classNames(projectcss.all, sty.rectangle13)}
                />

                <div
                  data-plasmic-name={"rectangle14"}
                  data-plasmic-override={overrides.rectangle14}
                  className={classNames(projectcss.all, sty.rectangle14)}
                />

                <div
                  data-plasmic-name={"rectangle15"}
                  data-plasmic-override={overrides.rectangle15}
                  className={classNames(projectcss.all, sty.rectangle15)}
                />

                <div
                  data-plasmic-name={"rectangle16"}
                  data-plasmic-override={overrides.rectangle16}
                  className={classNames(projectcss.all, sty.rectangle16)}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"group29"}
              data-plasmic-override={overrides.group29}
              className={classNames(projectcss.all, sty.group29)}
            >
              <div
                data-plasmic-name={"image4"}
                data-plasmic-override={overrides.image4}
                className={classNames(projectcss.all, sty.image4)}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___7AWjW)}
                displayHeight={"70px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"70px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/blank_project/images/btnPlay.svg",
                  fullWidth: 70,
                  fullHeight: 70,
                  aspectRatio: 1
                }}
              />
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kZtkR
              )}
            >
              {"And Boost Productivity"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___3Nv6P
              )}
            >
              {"SAVE MORE TIME"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__lKoEd
              )}
            >
              {
                "Your employees can bring any success into your\nbusiness, so we need to take care of them"
              }
            </div>

            <div
              data-plasmic-name={"input"}
              data-plasmic-override={overrides.input}
              className={classNames(projectcss.all, sty.input)}
            >
              <div
                data-plasmic-name={"rectangle4"}
                data-plasmic-override={overrides.rectangle4}
                className={classNames(projectcss.all, sty.rectangle4)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2VaVq
                )}
              >
                {"Email Address"}
              </div>
            </div>

            <div
              data-plasmic-name={"btnPrimary2"}
              data-plasmic-override={overrides.btnPrimary2}
              className={classNames(projectcss.all, sty.btnPrimary2)}
            >
              <div
                data-plasmic-name={"rectangle17"}
                data-plasmic-override={overrides.rectangle17}
                className={classNames(projectcss.all, sty.rectangle17)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__goEd
                )}
              >
                {"Get Started"}
              </div>
            </div>
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "landing",
    "navbar",
    "group1",
    "btnSecondary",
    "rectangle1",
    "logo",
    "group2",
    "rectangle3",
    "brand",
    "group14",
    "slack21",
    "group22",
    "group21",
    "group23",
    "group24",
    "group18",
    "group17",
    "group25",
    "group19",
    "group20",
    "group26",
    "group27",
    "group28",
    "btnPrimary",
    "link",
    "rectangle2",
    "group4",
    "image3",
    "group6",
    "rectangle5",
    "group5",
    "group7",
    "rectangle6",
    "group8",
    "group9",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "rectangle13",
    "rectangle14",
    "rectangle15",
    "rectangle16",
    "group29",
    "image4",
    "input",
    "rectangle4",
    "btnPrimary2",
    "rectangle17"
  ],
  landing: [
    "landing",
    "navbar",
    "group1",
    "btnSecondary",
    "rectangle1",
    "logo",
    "group2",
    "rectangle3",
    "brand",
    "group14",
    "slack21",
    "group22",
    "group21",
    "group23",
    "group24",
    "group18",
    "group17",
    "group25",
    "group19",
    "group20",
    "group26",
    "group27",
    "group28",
    "btnPrimary",
    "link",
    "rectangle2",
    "group4",
    "image3",
    "group6",
    "rectangle5",
    "group5",
    "group7",
    "rectangle6",
    "group8",
    "group9",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "rectangle13",
    "rectangle14",
    "rectangle15",
    "rectangle16",
    "group29",
    "image4",
    "input",
    "rectangle4",
    "btnPrimary2",
    "rectangle17"
  ],
  navbar: [
    "navbar",
    "group1",
    "btnSecondary",
    "rectangle1",
    "logo",
    "group2",
    "rectangle3"
  ],
  group1: ["group1"],
  btnSecondary: ["btnSecondary", "rectangle1"],
  rectangle1: ["rectangle1"],
  logo: ["logo", "group2", "rectangle3"],
  group2: ["group2", "rectangle3"],
  rectangle3: ["rectangle3"],
  brand: ["brand", "group14", "slack21"],
  group14: ["group14", "slack21"],
  slack21: ["slack21"],
  group22: ["group22", "group21"],
  group21: ["group21"],
  group23: ["group23", "group24"],
  group24: ["group24"],
  group18: ["group18", "group17"],
  group17: ["group17"],
  group25: ["group25", "group19"],
  group19: ["group19"],
  group20: ["group20", "group26"],
  group26: ["group26"],
  group27: ["group27", "group28"],
  group28: ["group28"],
  btnPrimary: ["btnPrimary", "link", "rectangle2"],
  link: ["link", "rectangle2"],
  rectangle2: ["rectangle2"],
  group4: ["group4", "image3"],
  image3: ["image3"],
  group6: ["group6", "rectangle5", "group5"],
  rectangle5: ["rectangle5"],
  group5: ["group5"],
  group7: [
    "group7",
    "rectangle6",
    "group8",
    "group9",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "rectangle13",
    "rectangle14",
    "rectangle15",
    "rectangle16"
  ],
  rectangle6: ["rectangle6"],
  group8: ["group8"],
  group9: [
    "group9",
    "rectangle7",
    "rectangle8",
    "rectangle9",
    "rectangle10",
    "rectangle11",
    "rectangle12",
    "rectangle13",
    "rectangle14",
    "rectangle15",
    "rectangle16"
  ],
  rectangle7: ["rectangle7"],
  rectangle8: ["rectangle8"],
  rectangle9: ["rectangle9"],
  rectangle10: ["rectangle10"],
  rectangle11: ["rectangle11"],
  rectangle12: ["rectangle12"],
  rectangle13: ["rectangle13"],
  rectangle14: ["rectangle14"],
  rectangle15: ["rectangle15"],
  rectangle16: ["rectangle16"],
  group29: ["group29", "image4"],
  image4: ["image4"],
  input: ["input", "rectangle4"],
  rectangle4: ["rectangle4"],
  btnPrimary2: ["btnPrimary2", "rectangle17"],
  rectangle17: ["rectangle17"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  landing: "div";
  navbar: "div";
  group1: "div";
  btnSecondary: "div";
  rectangle1: "div";
  logo: "div";
  group2: "div";
  rectangle3: "div";
  brand: "div";
  group14: "div";
  slack21: "div";
  group22: "div";
  group21: "div";
  group23: "div";
  group24: "div";
  group18: "div";
  group17: "div";
  group25: "div";
  group19: "div";
  group20: "div";
  group26: "div";
  group27: "div";
  group28: "div";
  btnPrimary: "div";
  link: "a";
  rectangle2: "a";
  group4: "div";
  image3: "div";
  group6: "div";
  rectangle5: "div";
  group5: "div";
  group7: "div";
  rectangle6: "div";
  group8: "div";
  group9: "div";
  rectangle7: "div";
  rectangle8: "div";
  rectangle9: "div";
  rectangle10: "div";
  rectangle11: "div";
  rectangle12: "div";
  rectangle13: "div";
  rectangle14: "div";
  rectangle15: "div";
  rectangle16: "div";
  group29: "div";
  image4: "div";
  input: "div";
  rectangle4: "div";
  btnPrimary2: "div";
  rectangle17: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    landing: makeNodeComponent("landing"),
    navbar: makeNodeComponent("navbar"),
    group1: makeNodeComponent("group1"),
    btnSecondary: makeNodeComponent("btnSecondary"),
    rectangle1: makeNodeComponent("rectangle1"),
    logo: makeNodeComponent("logo"),
    group2: makeNodeComponent("group2"),
    rectangle3: makeNodeComponent("rectangle3"),
    brand: makeNodeComponent("brand"),
    group14: makeNodeComponent("group14"),
    slack21: makeNodeComponent("slack21"),
    group22: makeNodeComponent("group22"),
    group21: makeNodeComponent("group21"),
    group23: makeNodeComponent("group23"),
    group24: makeNodeComponent("group24"),
    group18: makeNodeComponent("group18"),
    group17: makeNodeComponent("group17"),
    group25: makeNodeComponent("group25"),
    group19: makeNodeComponent("group19"),
    group20: makeNodeComponent("group20"),
    group26: makeNodeComponent("group26"),
    group27: makeNodeComponent("group27"),
    group28: makeNodeComponent("group28"),
    btnPrimary: makeNodeComponent("btnPrimary"),
    link: makeNodeComponent("link"),
    rectangle2: makeNodeComponent("rectangle2"),
    group4: makeNodeComponent("group4"),
    image3: makeNodeComponent("image3"),
    group6: makeNodeComponent("group6"),
    rectangle5: makeNodeComponent("rectangle5"),
    group5: makeNodeComponent("group5"),
    group7: makeNodeComponent("group7"),
    rectangle6: makeNodeComponent("rectangle6"),
    group8: makeNodeComponent("group8"),
    group9: makeNodeComponent("group9"),
    rectangle7: makeNodeComponent("rectangle7"),
    rectangle8: makeNodeComponent("rectangle8"),
    rectangle9: makeNodeComponent("rectangle9"),
    rectangle10: makeNodeComponent("rectangle10"),
    rectangle11: makeNodeComponent("rectangle11"),
    rectangle12: makeNodeComponent("rectangle12"),
    rectangle13: makeNodeComponent("rectangle13"),
    rectangle14: makeNodeComponent("rectangle14"),
    rectangle15: makeNodeComponent("rectangle15"),
    rectangle16: makeNodeComponent("rectangle16"),
    group29: makeNodeComponent("group29"),
    image4: makeNodeComponent("image4"),
    input: makeNodeComponent("input"),
    rectangle4: makeNodeComponent("rectangle4"),
    btnPrimary2: makeNodeComponent("btnPrimary2"),
    rectangle17: makeNodeComponent("rectangle17"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
